apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotnet-todo.fullname" . }}
  labels:
    {{- include "dotnet-todo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dotnet-todo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dotnet-todo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: dotnet-todo
      imagePullSecrets:
      - name: aws-ecr-credentials
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
